### ISSUE TITLE
mongodb按_id查询无结果、ObjectID is not defined

### ISSUE THREAD

**Issue by famanoder** [famanoder/V#1]
不像mongoose里可以直接db.cols.find(_id:'5867fddf4aee37201fb4d1d3')；
直接的mongodb操作，_id为Object，所以需要使用ObjectID查询：
import BSON from 'BSON';
cx.mongo.db('dbname').collection('cols').find(_id:BSON.ObjectID('5867fddf4aee37201fb4d1d3')).toArray(cb);

**Comment by rowthan** [comment]
怎么不用mongoose呢？ 是效率的问题吗？

**Comment by famanoder** [comment]
mongoose挺好啊，就是跨站时models文件不方便
